# Tests for the generated boundary-zones object (bin/export_boundaries.jl).
#
# The pillar-6 surface's claim is that the ELASTIC structure is GENERATED by walking
# ZONE_PROFILES's BoundaryBook structs — never hand-kept — while the measured effects
# and the fixed-neighbour list are the ONE curated-but-cited input (frozen experiment
# outcomes + facts that carry no struct). These tests make that enforceable:
#   - every BoundaryBook carried on a footprint profile resolves to a KNOWN const name
#     (a new book without a name mapping emits "UNKNOWN_BOOK" and fails here);
#   - every effect key in docs/pillars/boundary-effects.json is realised by a real book,
#     cites a committed doc, and names a cv <= the code version;
#   - every FIXED counterparty is a real out-of-footprint network neighbour (so the
#     list cannot drift into fiction), carries the "NOT a book" correction/roadmap,
#     and has NO struct in ZONE_PROFILES (the blank is the point);
#   - the exporter transcribes no boundary number and does not auto-publish.

using Test, Dates, JSON
using Euphemia
const _MO = Euphemia.MeritOrderBook

@testset "Boundaries export" begin

    # Walk the footprint the exporter walks.
    include(joinpath(dirname(@__DIR__), "bin", "forecast_common.jl"))
    footprint = FORECAST_FOOTPRINT

    # Distinct books carried on any footprint profile.
    carried = Dict{_MO.BoundaryBook,Vector{String}}()
    for z in footprint
        b = _MO.get_zone_profile(z).boundary_book
        b === nothing && continue
        push!(get!(carried, b, String[]), z)
    end

    effects_path = joinpath(dirname(@__DIR__), "docs", "pillars", "boundary-effects.json")
    doc = JSON.parsefile(effects_path)

    _name(b) =
        b == _MO.VIKING_GB_BOOK ? "VIKING_GB_BOOK" :
        b == _MO.GB_FR_BOOK ? "GB_FR_BOOK" :
        (b == _MO.UA_BOOK_DEFAULT || b == _MO.UA_BOOK_PL) ? "UA_BOOK" : "UNKNOWN_BOOK"

    @testset "every carried book resolves to a known const name" begin
        @test !isempty(carried)   # the footprint must carry SOME boundary book
        for (b, _) in carried
            @test _name(b) != "UNKNOWN_BOOK"
            @test !isempty(b.counterparty)
            @test b.anchor in (:gb_ccgt_srmc, :zone_gas_srmc)
            @test b.capability_mode in (:atc_capped, :p95_block)
            @test !isempty(b.disable_env)
        end
        # The two boundary programs we document are both live on the footprint.
        realized = Set(_name(b) for b in keys(carried))
        @test "VIKING_GB_BOOK" in realized
        @test "GB_FR_BOOK" in realized
        @test "UA_BOOK" in realized
    end

    @testset "GB books are two INDEPENDENT books with different carbon legs" begin
        # The load-bearing honesty detail: DK1/Viking uses EUA, FR uses UKA.
        @test _MO.VIKING_GB_BOOK.carbon_source === :eua
        @test _MO.GB_FR_BOOK.carbon_source === :uka
        @test _MO.VIKING_GB_BOOK.anchor_mult == 1.15
        @test _MO.GB_FR_BOOK.anchor_mult == 1.15
        # the FR↔GB double-count fix: it strips MORE codes than it sizes ATC on.
        @test length(_MO.boundary_net_exclude(_MO.GB_FR_BOOK)) >
              length(_MO.GB_FR_BOOK.flow_codes)
        @test "GB_IFA" in _MO.boundary_net_exclude(_MO.GB_FR_BOOK)
    end

    @testset "UA is a firm-slice buyer with the generic-anchor weakness stated" begin
        @test _MO.UA_BOOK_DEFAULT.firm_slice
        @test _MO.UA_BOOK_DEFAULT.anchor === :zone_gas_srmc   # the documented weakness
        @test _MO.UA_BOOK_DEFAULT.capability_mode === :p95_block
        @test "UA_DobTPP" in _MO.UA_BOOK_PL.flow_codes        # PL's radial
        @test !("UA_DobTPP" in _MO.UA_BOOK_DEFAULT.flow_codes)
    end

    @testset "every effect key is realised by a book, cited, version-bounded" begin
        realized = Set(_name(b) for b in keys(carried))
        for (name, eff) in doc["effects"]
            @test name in realized                    # no effect for a phantom book
            @test eff["cv"] isa Integer
            @test eff["cv"] <= Euphemia.ENERGY_PRICES_CODE_VERSION
            docpath = joinpath(dirname(@__DIR__), eff["doc"])
            @test ispath(docpath)                     # the cited experiment exists
        end
    end

    @testset "fixed neighbours are real network neighbours with NO struct" begin
        # The GR/BG neighbour set includes the out-of-footprint fixed injections.
        # Cross-check TR/AL/MK are genuine neighbours (Network.jl), never in the
        # footprint, and carry no boundary book.
        @test !isempty(doc["fixed"])
        for f in doc["fixed"]
            cp = f["counterparty"]
            @test !(cp in footprint)                  # never in the footprint
            @test f["book"] === nothing               # the blank IS the point
            @test !isempty(f["borders"])
            for bz in f["borders"]
                @test bz in footprint                 # the border zone IS in-footprint
            end
        end
        # TR must carry the verbatim "NOT a book" correction + the concrete roadmap.
        tr = only(filter(f -> f["counterparty"] == "TR", doc["fixed"]))
        @test occursin("It is neither", tr["correction"])
        @test occursin("BOTAS", tr["roadmap"][1]) || occursin("Akkuyu", tr["roadmap"][1])
        @test length(tr["roadmap"]) == 3
    end

    @testset "the flow rule is the :v3 ex-ante default + the lookahead audit note" begin
        fr = doc["flow_rule"]
        @test fr["footprint_default"] == "v3"
        @test fr["legacy"] == "d0"
        @test occursin("caught our own lookahead", fr["audit_note"])
        @test ispath(joinpath(dirname(@__DIR__), fr["doc"]))
    end

    @testset "the exporter walks structs and does not auto-publish" begin
        src = read(joinpath(dirname(@__DIR__), "bin", "export_boundaries.jl"), String)
        @test occursin("get_zone_profile", src)              # walks the registry
        @test occursin("boundary_book", src)
        @test occursin("BoundaryBook", src)
        @test occursin("boundary-effects.json", src)         # reads the cited file
        @test !occursin("const VIKING_GB_BOOK", src)         # transcribes no book
        @test occursin("BOUNDARIES_OUT", src)
        @test occursin("data\", \"calibration\"", src)       # writes outside web tree
        @test !occursin("WEB_PARQUET_OUT", src)
    end
end
