/* DOM smoke test for pillar 6 — the #view=boundary surface — driven through a
 * dependency-free DOM stub (no jsdom), the same technique as method_view.test.mjs.
 *
 * Feeds app.js the committed boundaries FIXTURE (the exact JSON the SPA renders,
 * generated by bin/export_boundaries.jl), then asserts:
 *   1. the ring builds one node per named neighbour (GB one node / two edges, UA
 *      one node / four edges, TR/AL/MK fixed) with the elastic/fixed legend;
 *   2. the per-country cards fill the common skeleton — GB shows BOTH carbon legs
 *      (eua + uka) and the double-count exhibit; UA shows the firm slice, the
 *      generic-anchor weakness, and the HU-March lesson; TR shows the verbatim
 *      "NOT a book" correction + the 3-step roadmap + blank anchor;
 *   3. every measured score is QUOTED from the fixture (before→after arrows), never
 *      recomputed;
 *   4. the :v3 flow-rule panel carries the cv25 "caught our own lookahead" note.
 *
 * The fixture lives under workers/api/test/fixtures/ (never shipped to the site).
 */
import { readFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const here = dirname(fileURLToPath(import.meta.url));
const appPath = join(here, "../../../web/app.js");
const boundaries = JSON.parse(readFileSync(join(here, "fixtures/boundaries.json"), "utf8"));

let failures = 0;
function ok(cond, msg) { if (!cond) { failures++; console.error("FAIL: " + msg); } else { console.log("ok - " + msg); } }

/* ---- minimal DOM stub (id registry + svg + classList.toggle) ---- */
class El {
  constructor(tag) {
    this.tagName = tag; this.className = ""; this.children = []; this._text = null;
    this.attrs = {}; this.hidden = false; this._handlers = {}; this.style = {}; this.dataset = {};
    this.value = ""; this.max = "0";
    const self = this;
    this.classList = {
      add(c) { if (!self._classes().includes(c)) self.className = (self.className + " " + c).trim(); },
      remove(c) { self.className = self._classes().filter((x) => x !== c).join(" "); },
      toggle(c, on) { const has = self._classes().includes(c); const want = on === undefined ? !has : on; want ? this.add(c) : this.remove(c); return want; },
      contains(c) { return self._classes().includes(c); },
    };
  }
  _classes() { return this.className.split(/\s+/).filter(Boolean); }
  appendChild(c) { this.children.push(c); if (c instanceof El) c.parentNode = this; return c; }
  removeChild(c) { this.children = this.children.filter((x) => x !== c); return c; }
  setAttribute(k, v) { this.attrs[k] = String(v); if (k === "class") this.className = String(v); }
  getAttribute(k) { return this.attrs[k] === undefined ? null : this.attrs[k]; }
  addEventListener(t, fn) { (this._handlers[t] || (this._handlers[t] = [])).push(fn); }
  removeEventListener() {}
  _fire(t, ev) { (this._handlers[t] || []).forEach((fn) => fn(ev || { preventDefault() {}, stopPropagation() {} })); }
  getBoundingClientRect() { return { top: 0, bottom: 0, left: 0, right: 0 }; }
  scrollIntoView() {}
  set textContent(v) { this.children = []; this._text = v == null ? "" : String(v); }
  get textContent() {
    let s = this._text || "";
    for (const c of this.children) s += c instanceof El ? c.textContent : (c.nodeValue || "");
    return s;
  }
  _all(pred, out) { for (const c of this.children) if (c instanceof El) { if (pred(c)) out.push(c); c._all(pred, out); } return out; }
  _pred(sel) {
    if (sel[0] === ".") { const cls = sel.slice(1); return (e) => e._classes().includes(cls); }
    const tag = sel.toLowerCase(); return (e) => e.tagName && e.tagName.toLowerCase() === tag;
  }
  querySelector(sel) { const r = this._all(this._pred(sel), []); return r[0] || null; }
  querySelectorAll(sel) { const r = this._all(this._pred(sel), []); r.forEach = Array.prototype.forEach.bind(r); return r; }
}
const registry = {};
function byId(id) { return registry[id] || (registry[id] = new El("div")); }
globalThis.window = {
  location: { search: "", hash: "" }, __EUPHEMIA_NO_AUTOINIT: true,
  scrollX: 0, scrollY: 0, innerWidth: 1200, addEventListener() {}, setTimeout: setTimeout,
};
globalThis.document = {
  documentElement: new El("html"), body: new El("body"),
  createElement: (t) => new El(t), createElementNS: (_ns, t) => new El(t),
  createTextNode: (t) => ({ nodeValue: String(t) }),
  getElementById: byId,
  querySelectorAll: () => { const a = []; a.forEach = Array.prototype.forEach.bind(a); return a; },
  addEventListener() {}, removeEventListener() {},
};
globalThis.getComputedStyle = () => ({ getPropertyValue: () => "#888888" });
// map/flows/book best-effort loads: reject so the static ring/cards render alone.
globalThis.fetch = () => Promise.reject(new Error("live API absent (static-only test)"));

await import(appPath);
const api = globalThis.window.__euphemiaBook;
ok(api && typeof api.renderBoundary === "function", "app.js exposed the boundary test surface");

const tick = () => new Promise((r) => setTimeout(r, 0));
async function settle() { for (let i = 0; i < 8; i++) await tick(); }

/* ---- render the boundary view from the fixture ---- */
api.setBoundaries(boundaries);
api.state.view = "boundary";
await api.renderBoundary();
await settle();

/* ---- 1. the ring ---- */
{
  const nodes = api.boundaryNodes(boundaries);
  const gb = nodes.find((n) => n.counterparty === "GB");
  const ua = nodes.find((n) => n.counterparty === "UA");
  ok(gb && gb.kind === "elastic" && gb.edges.length === 2, "ring: GB is ONE node with TWO edges (D1)");
  ok(ua && ua.kind === "elastic" && ua.edges.length === 4, "ring: UA is ONE node with FOUR edges");
  ok(nodes.filter((n) => n.kind === "fixed").length === 3, "ring: three fixed nodes (TR/AL/MK)");

  const ring = byId("boundary-ring");
  ok(ring.querySelector("svg"), "ring: an SVG is drawn");
  ok(ring.querySelectorAll(".boundary-node").length >= 5, "ring: >=5 neighbour node markers");
  const legend = byId("boundary-ring-legend");
  ok(/elastic counterparty/.test(legend.textContent) && /fixed observed injection/.test(legend.textContent),
     "ring: legend states the elastic/fixed wall");
}

/* ---- 2. the per-country cards (asserted against the cards host — the stub's
        getElementById does not index the card.id assigned at build time) ---- */
{
  const cards = byId("boundary-cards");
  const txt = cards.textContent;
  ok(cards.querySelectorAll(".boundary-card").length === 5, "cards: one card per named neighbour (5)");
  ok(cards.querySelectorAll(".boundary-card-elastic").length === 2, "cards: two elastic cards (GB, UA)");
  ok(cards.querySelectorAll(".boundary-card-fixed").length === 3, "cards: three fixed cards (TR/AL/MK)");

  // KIND badges
  ok(cards.querySelectorAll(".kind-elastic").length >= 2, "cards: elastic KIND badges present");
  ok(cards.querySelectorAll(".kind-fixed").length >= 3, "cards: fixed KIND badges present");

  // GB: both carbon legs + double-count exhibit + parked-zone note (GB is the only
  // card mentioning any of these tokens, so whole-host matching is unambiguous).
  ok(/:eua/.test(txt) && /:uka/.test(txt), "GB card: shows BOTH carbon legs (eua + uka)");
  ok(/PARKED/.test(txt), "GB card: states GB the zone is PARKED");
  ok(/double-count/i.test(txt) && /GB_IFA/.test(txt), "GB card: the FR↔GB double-count exhibit");
  ok(/HALF of a two-bug lever/.test(txt), "GB card: FR book labelled half of a two-bug lever");

  // UA: firm slice + generic-anchor weakness + HU-March lesson
  ok(/firm/i.test(txt), "UA card: firm slice surfaced");
  ok(/generic/i.test(txt) && /no UA feed|no counterparty feed/i.test(txt),
     "UA card: generic-anchor weakness stated in the open");
  ok(/HU-March lesson/.test(txt) && /breach/i.test(txt), "UA card: the HU-March lesson exhibit");
  ok(/Accepted residuals/.test(txt) && /33\.0/.test(txt), "UA card: accepted residuals shown at equal weight");

  // TR/AL/MK: the verbatim "NOT a book" correction + 3-step roadmap + blank anchor
  ok(/It is neither/.test(txt), "TR card: verbatim 'NOT a book' correction");
  ok(/none \(not a model\)/.test(txt), "fixed cards: anchor blank — 'none (not a model)'");
  ok(/BOTAS|Akkuyu/.test(txt), "TR card: what-a-TR-book-would-need roadmap");
  ok(cards.querySelectorAll(".boundary-roadmap-list").length === 1,
     "TR card: the roadmap is a real list");
}

/* ---- 3. measured scores QUOTED (before→after), never recomputed ---- */
{
  const cards = byId("boundary-cards").textContent;
  ok(/31\.50 → 28\.30/.test(cards) || /31\.5 → 28\.3/.test(cards), "quoted: DK1 Viking July MAE 31.5→28.3");
  ok(/72\.30 → 57\.10/.test(cards) || /72\.3 → 57\.1/.test(cards), "quoted: HU July MAE 72.3→57.1");
  ok(/0\.55 → 0\.80/.test(cards), "quoted: DK1 March corr 0.55→0.80");
}

/* ---- 4. the :v3 flow-rule panel + cv25 lookahead audit ---- */
{
  const fr = byId("boundary-flowrule").textContent;
  ok(/:v3/.test(fr) && /load-analogue/i.test(fr), "flow rule: :v3 load-analogue rule explained");
  ok(/legacy/i.test(fr) && /:d0/.test(fr), "flow rule: :d0 named as legacy only");
  const audit = byId("boundary-flowrule-audit").textContent;
  ok(/caught our own lookahead/i.test(audit), "flow rule: the cv25 lookahead-audit note");
}

if (failures) {
  console.error(`\nboundary_view: ${failures} FAILURE(S)`);
  process.exit(1);
}
console.log("\nboundary_view: ALL ASSERTIONS PASSED (ring + cards + quoted scores + flow rule)");
